add_header Cache-Control "public, max-age=31536000, immutable";
etag on;
gzip_static on;
gzip on;
gzip_min_length 1024;
gzip_comp_level 5;
gzip_proxied any;
gzip_types text/css text/javascript application/javascript application/json image/svg+xml;
access_log off;
